### ISSUE TITLE
getMissionsNext

### ISSUE THREAD

**Issue by sign0** [meriadec/node-ratp#1]
Salut,

Je n'arrive pas à faire fonctionner la méthode getMissionsNext en mode realm="r" (Ni manuellement avec le package SOAP ni avec ton package node-ratp). J'ai éssayé toutes les configurations possibles pour l'exemple ci dessous, mais ça mouline...

`const payload = {
		"station": {
	    "id": "274_786_845",
    	"line": {
	  		"id": "B274",
	  		"codeStif": "100100274",
	  		"realm": "r"
	  	},
	    "name": "Les bateliers",
	  },
	  "direction": {
			"sens": "A",
		}
	};`

Est-ce que tu aurais un exemple de "playload" qui fonctionne pour getMissionsNext en realm="r" ? :)

Merci

**Comment by meriadec** [comment]
Hello,

Premiere chose: est-ce que l'ip que tu as utilisée est bien l'une de celles renseignées lors de l'inscription?  (cf https://data.ratp.fr/page/temps-reel/). Si ça mouline sans faire d'erreurs c'est surement ça.

Au niveau de ta payload, en effet elle n'est pas correcte (`Unexpected subelement codeStif`). 
La doc RATP est vraiment pas géniale, je te conseille d'ouvrir le fichier `Wsiv.wsdl` contenu dans le kit de developpement de RATP (ou dans ce repo) avec un outil SOAP graphique (perso j'ai découvert Soap UI https://www.soapui.org/).

En bidouillant a droite à gauche (l'ordre des props est important, etc), j'ai pu assez vite récupérer un résultat pour la station que tu a passé en exemple:

![screen shot 2017-01-29 at 22 34 27](https://cloud.githubusercontent.com/assets/315259/22408100/2e8c3780-e673-11e6-9e32-0ce2cab57563.png)

Bon courage !
