### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by TomFevrier** [meriadec/node-ratp#2]
Hello,

Every time I try to install the node package via npm I get errors:
`Command failed: git clone (...)` and `Permission denied (publickey)`.

Any idea about why I am unable to clone the repo through node?

Thank you!

**Comment by meriadec** [comment]
what do you mean by clone the repo through node?

you may find help here https://help.github.com/articles/error-permission-denied-publickey/

**Comment by TomFevrier** [comment]
I simply did `npm install ratp`, and it gave me these errors...

**Comment by meriadec** [comment]
OK got it. (you can still resolve the issue by generating ssh-keys for your github account)

If you really want to not use ssh, I guess you can try this: https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe

**Comment by TomFevrier** [comment]
La deuxième solution ne marche pas, comment générer les clés vers mon compte GitHub ? Comment se fait-il que cela ne marche pas avec npm tout simplement ?

**Comment by meriadec** [comment]
for ssh-key generation you can check the github help: https://help.github.com/enterprise/2.14/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

node-soap dependency comes directly from github, and npm resolves it with ssh: URI. [cf doc](https://docs.npmjs.com/files/package.json#repository)
