### ISSUE TITLE
node-soap n'existe plus

### ISSUE THREAD

**Issue by wadouk** [meriadec/node-ratp#3]
du coup impossible d'installer ce paquet, m'aurait bien aider pourtant

**Comment by meriadec** [comment]
hmm ouais.. j'avais forké [vpulim/node-soap](https://github.com/vpulim/node-soap) pour fixer un truc ya 2 ans.. mais je sais plus quoi.. faudrait re-essayer maintenant avec le vrai paquet en dependence (a changer [ici](https://github.com/meriadec/node-ratp/blob/master/package.json#L57))
